import 'package:isar/isar.dart';

part 'cached_session.g.dart';

/// Locally cached session summary from the Hermes Agent API Server.
///
/// Mirrors the server-side session but stored locally for offline access.
/// Uses soft-delete (isDeleted + deletedAt) per DEC-034 rule 7.
/// TTL: 7 days — sessions older than this are considered stale.
@collection
class CachedSession {
  /// Isar auto-increment primary key (internal).
  Id id = Isar.autoIncrement;

  /// Server-assigned session ID — the canonical identifier from the API.
  @Index(unique: true, replace: true)
  late String sessionId;

  /// FK — which ServerConfig this session belongs to.
  @Index()
  late String serverId;

  /// Session title (may be auto-generated by server).
  String? title;

  /// Model used for this session.
  String? modelName;

  /// Number of messages in the session.
  late int messageCount;

  /// Timestamp of last activity on the server.
  late DateTime lastActivity;

  /// User-pinned session.
  late bool isPinned;

  /// User-archived session.
  late bool isArchived;

  /// When this cache entry was created/updated locally.
  late DateTime cachedAt;

  // ─── Soft Delete (DEC-034, Anti-Ghost Protocol) ───

  /// Soft-delete flag. Application-level hard deletes are forbidden.
  @Index()
  late bool isDeleted;

  /// Timestamp when soft-deleted. Null if not deleted.
  DateTime? deletedAt;

  CachedSession({
    this.id = Isar.autoIncrement,
    required this.sessionId,
    required this.serverId,
    this.title,
    this.modelName,
    this.messageCount = 0,
    required this.lastActivity,
    this.isPinned = false,
    this.isArchived = false,
    required this.cachedAt,
    this.isDeleted = false,
    this.deletedAt,
  });
}
